version: "3"

services:
  web:
    image: nginx:1.19
    container_name: movies2_web
    ports:
      - 8105:80
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/1.19/local.website.conf:/etc/nginx/conf.d/default.conf
    networks:
      - net-movies2

  app:
    extra_hosts:
      - "host.docker.internal:host-gateway"         # Usado por x-debug
    build:
      context: .
      dockerfile: Dockerfile
      args:
       - WITH_XDEBUG=true
    container_name: movies2_app
    volumes:
      - ./:/var/www/html/
      - ./docker/php/7.4/php.ini:/usr/local/etc/php/php.ini
      - ./docker/php/7.4/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    environment:
      PHP_IDE_CONFIG: "serverName=docker-cli"       # server en PHPStorm
    working_dir: /var/www/html
    networks:
      - net-movies2

  db:
    image: mysql:5.7.22
    container_name: movies2_db
    restart: unless-stopped
    tty: true
    ports:
      - "3404:3306"
    environment:
      MYSQL_DATABASE: movies2                # Crea la db (si no existe)
      MYSQL_ROOT_PASSWORD: admin            # usando esta contraseña
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ~/Data/movies2:/var/lib/mysql
      - ./docker/mysql/5.7.22/my.cnf:/etc/mysql/my.cnf
    networks:
      - net-movies2

networks:
  net-movies2:
    driver: bridge

